version: '3.9'
services:
    nats:
        image: 'nats:latest'
        container_name: nats-server
        ports:
            - '6222:6222'
            - '8222:8222'
            - '4222:4222'
        command: '-js -m 8222'
